### ISSUE TITLE
Youth grantees

### ISSUE THREAD

**Issue by Dunstonlwangas** [TSSlade/tusome_db#5]
Just wondering how to fit in the youth grantees and partners that we are collaborating with.

**Comment by TSSlade** [comment]
Very good point, DK. I think we'd want to have some kind of _entity-based_ data structure or list for the grantees at the group level, with their key personnel included in the _lists of persons_ for whom we maintain data on contact information, roles, affiliations, job groups, etc.

How important do you think it is for us to map their activities into some kind of activity-based data structure? Are we reporting on their participants and attendees as part of our indicators for USAID?

**Comment by Dunstonlwangas** [comment]
for youth grantees is simply the number of youth grantees supported. No detailed information required. But since we are looking at this as futuristic element, we might need to have an allocation of youth grantees and partners. I also read about the Elimu yetu coalition and the like

**Comment by Lwambari** [comment]
On this we might want to have a list of all the youth groups in Kenya and their contact groups+their group leaders-presidents etc. This is a good data set when sending out new calls for proposal.

**Comment by TSSlade** [comment]
Lucy - I think maintaining a list of all youth groups in Kenya might be a bit outside our scope. (That could take a lot of time to track down and vet the necessary information.) That said, I agree with your point that we want a way to easily extract the information we require to issue RFPs and the like. I'd suggest we handle that just by having the structure/framework for recording their information available, and update it in the moment as new information comes in, rather than necessarily proactively seeking out all of the data.

**Comment by TSSlade** [comment]
Sorry, @Dunstonlwangas - I realized I didn't address your broader point, which is that we ought to be thinking about how we track partnership engagements. This could be Elimu Yetu, but it could also be things like the iMlango partnership, the KnowZone partnership, the LMS/Mercy Corps partnership, etc.

Would you mind including some language in your new PR about what that might look like? Presumably this is still in the *entity-based* section of our proposed schema, right?
